version: '3'

services:

    mysql:
        build: ./requirements/mariadb
        volumes:
            - mysql:/var/lib/mysql
        env_file:
            - .env
        restart: always
        ports:
            - 3306:3306
        networks:
            - inception_network

    wordpress:
        build: ./requirements/wordpress

        volumes:
            - wordpress:/var/www/html
        env_file:
            - .env
        depends_on:
            - mysql
        restart: always
        ports:
            - 9000:9000
        networks:
            - inception_network

    nginx:
        build: ./requirements/nginx
        volumes:
            - ./requirements/nginx:/etc/nginx/conf.d
            - wordpress:/var/www/html
        links:
            - wordpress
        restart: always
        ports:
            - 443:443
        networks:
            - inception_network

networks:
    inception_network:
        driver: bridge

volumes:
    mysql:
        driver: local
        driver_opts:
            type: none
            device: /home/sgaubert/data/mysql
            o: bind
    wordpress:
        driver: local
        driver_opts:
            type: none
            device: /home/sgaubert/data/wordpress
            o: bind