version: '3.9'

services:

    mysql:
        build: ./requirements/mariadb
        volumes:
            - dbdata:/var/lib/mysql
        env_file:
            - .env
        restart: unless-stopped
        networks:
            - inception_network

    wordpress:
        build: ./requirements/wordpress

        volumes:
            - wpdata:/var/www/html
        env_file:
            - .env
        depends_on:
            - mysql
        restart: unless-stopped
        networks:
            - inception_network

    nginx:
        build: ./requirements/nginx
        volumes:
        #    - ./requirements/nginx:/etc/nginx/conf.d
            - wpdata:/var/www/html
        # links:
        #     - wordpress
        restart: unless-stopped
        ports:
            - "443:443"
        depends_on:
            - wordpress
        networks:
            - inception_network

networks:
    inception_network:
        driver: bridge

volumes:
    dbdata:
        # driver: local
        # driver_opts:
        #     type: none
        #     device: ~/data/mysql
        #     o: bind
    wpdata:
        # driver: local
        # driver_opts:
        #     type: none
        #     device: ~/data/wordpress
        #     o: bind
